### PR TITLE
feat: set specific hydra-genetics version

### PR DESCRIPTION
**Pull request by Smeds**

### CODE REVIEW

**Review by ljmesi — APPROVED** [review]
Looks good to me.

**Comment by pyrevo** [comment]
> `hydra-genetics==0.10.0`

Thanks, should we update it to `hydra-genetics==0.11.0` now that the new version is out?

**Comment by Smeds** [comment]
> > `hydra-genetics==0.10.0`
> 
> Thanks, should we update it to `hydra-genetics==0.11.0` now that the new version is out?

Yes! I would go with 0.11.0 now

**Comment by Smeds** [comment]
> > > `hydra-genetics==0.10.0`
> > 
> > 
> > Thanks, should we update it to `hydra-genetics==0.11.0` now that the new version is out?
> 
> Yes! I would go with 0.11.0 now

I have updated the pull-request

**Pull request closed without merging**
